package main

import (
	"path/filepath"
	"strings"
	"testing"

	"ui_console/orchestration/go_program"
	"ui_console/orchestration/skill_step"
)

func TestIsSkillUsageRequest(t *testing.T) {
	for _, in := range []string{"產出電料Bom這個skill怎麼用？", "穿衣建議 用法", "這個如何使用"} {
		if !isSkillUsageRequest(in) {
			t.Fatalf("should detect usage intent: %q", in)
		}
	}
	for _, in := range []string{"你有看到我放進去的檔案嗎？", "幫我產出電料BOM"} {
		if isSkillUsageRequest(in) {
			t.Fatalf("should NOT be usage intent: %q", in)
		}
	}
}

func TestBuildGoProgramSkillDescription(t *testing.T) {
	d := buildGoProgramSkillDescription(go_program.Manifest{
		Purpose:      "交叉比對電料 BOM 與編碼表並產出整合 BOM",
		InputSchema:  go_program.ObjectSchema{Required: []string{"電料BOM", "編碼紀錄"}},
		OutputSchema: go_program.ObjectSchema{Required: []string{"整合BOM"}},
	})
	for _, want := range []string{"交叉比對", "需要輸入：電料BOM、編碼紀錄", "輸出：整合BOM"} {
		if !strings.Contains(d, want) {
			t.Fatalf("description missing %q: %s", want, d)
		}
	}
	// 佔位 purpose 要被換成可讀預設值。
	d2 := buildGoProgramSkillDescription(go_program.Manifest{Purpose: "pending program skill generated by ..."})
	if strings.Contains(strings.ToLower(d2), "pending program skill") {
		t.Fatalf("placeholder purpose should be replaced: %s", d2)
	}
}

func TestFormatSkillUsageCard(t *testing.T) {
	app := &App{}
	withDesc := app.formatSkillUsageCard(skill_step.SkillManifest{
		DisplayName: "產出電料Bom",
		Description: "交叉比對兩張表產出 BOM；需要輸入：電料BOM、編碼紀錄",
	})
	if !strings.Contains(withDesc, "產出電料Bom") || !strings.Contains(withDesc, "需要輸入") {
		t.Fatalf("usage card missing name/desc: %s", withDesc)
	}
	// Description 空 → 應誠實提示去哪補。
	empty := app.formatSkillUsageCard(skill_step.SkillManifest{DisplayName: "X"})
	if !strings.Contains(empty, "尚未填寫用法說明") {
		t.Fatalf("empty-desc card should point user where to fill: %s", empty)
	}
}

func TestSynthesizeSkillDescription(t *testing.T) {
	d := synthesizeSkillDescription(skill_step.SkillManifest{
		DisplayName: "產出電料Bom",
		Tags:        skill_step.SkillTags{ActionTag: []string{"程式"}, DomainTag: []string{"產出電料Bom"}},
	})
	if !strings.Contains(d, "產出電料Bom") || !strings.Contains(d, "動作：程式") {
		t.Fatalf("synthesized desc missing name/action: %s", d)
	}
	// DomainTag 等於名稱時不應贅述成「領域：產出電料Bom」。
	if strings.Contains(d, "領域：產出電料Bom") {
		t.Fatalf("domain == name should be skipped: %s", d)
	}
	if strings.TrimSpace(d) == "" {
		t.Fatal("should never be empty")
	}
}

func TestBackfillSkillDescriptionsWritesFallbackAndHash(t *testing.T) {
	root := t.TempDir()
	archive := skill_step.NewArchiveService(root)
	manifest := &skill_step.SkillManifest{
		SchemaVersion:  skill_step.SchemaManifestV1,
		SkillID:        "go-program-產出電料bom",
		DisplayName:    "產出電料Bom",
		Version:        "0.1.0",
		DescriptionDoc: "README.md",
		Tags: skill_step.SkillTags{
			PurposeTag: []string{"go_program", "authoring_loop"},
			ActionTag:  []string{"程式"},
			DomainTag:  []string{"產出電料Bom"},
			RiskTag:    []string{"medium"},
		},
		Permissions: skill_step.SkillPermissions{
			Filesystem: "app_data_read_outputs_scratch",
			Execution:  "controlled",
		},
	}
	saved, err := archive.SavePendingDraft(manifest)
	if err != nil {
		t.Fatalf("save pending draft: %v", err)
	}
	oldHash := saved.Hash

	app := &App{skillArchive: archive}
	app.backfillSkillDescriptions("test")

	loaded, err := skill_step.LoadManifest(filepath.Join(root, "data", "skills", manifest.SkillID, "skill_manifest.json"))
	if err != nil {
		t.Fatalf("load manifest: %v", err)
	}
	if strings.TrimSpace(loaded.Description) == "" {
		t.Fatal("backfill should persist a non-empty description")
	}
	for _, want := range []string{"機台", "電料BOM", "編碼紀錄", "整合後電料BOM表"} {
		if !strings.Contains(loaded.Description, want) {
			t.Fatalf("description missing %q: %s", want, loaded.Description)
		}
	}
	if loaded.Hash == "" || loaded.Hash == oldHash || loaded.HashMismatch {
		t.Fatalf("hash should be recomputed cleanly, old=%q loaded=%q mismatch=%v", oldHash, loaded.Hash, loaded.HashMismatch)
	}
}

func TestBackfillSkillDescriptionsUpgradesFallbackOnly(t *testing.T) {
	root := t.TempDir()
	archive := skill_step.NewArchiveService(root)
	fallbackManifest := &skill_step.SkillManifest{
		SchemaVersion:  skill_step.SchemaManifestV1,
		SkillID:        "go-program-program-2c889620-skill-1781019832374554000",
		DisplayName:    "產出電料Bom",
		Version:        "1.0.0",
		DescriptionDoc: "README.md",
		Tags: skill_step.SkillTags{
			DomainTag: []string{"產出電料Bom"},
		},
		Description: "「產出電料Bom」技能；使用時請說明要它做什麼並附上需要的資料或先載入相關檔案",
	}
	if _, err := archive.SavePendingDraft(fallbackManifest); err != nil {
		t.Fatalf("save fallback draft: %v", err)
	}
	customManifest := &skill_step.SkillManifest{
		SchemaVersion:  skill_step.SchemaManifestV1,
		SkillID:        "custom-skill",
		DisplayName:    "產出電料Bom 客製",
		Version:        "1.0.0",
		DescriptionDoc: "README.md",
		Description:    "這是使用者手動填寫的特殊說明，不應被覆蓋。",
	}
	if _, err := archive.SavePendingDraft(customManifest); err != nil {
		t.Fatalf("save custom draft: %v", err)
	}

	app := &App{skillArchive: archive}
	app.backfillSkillDescriptions("test")

	upgraded, err := skill_step.LoadManifest(filepath.Join(root, "data", "skills", fallbackManifest.SkillID, "skill_manifest.json"))
	if err != nil {
		t.Fatalf("load upgraded manifest: %v", err)
	}
	for _, want := range []string{"機台", "電料BOM", "編碼紀錄", "整合後電料BOM表"} {
		if !strings.Contains(upgraded.Description, want) {
			t.Fatalf("upgraded description missing %q: %s", want, upgraded.Description)
		}
	}

	kept, err := skill_step.LoadManifest(filepath.Join(root, "data", "skills", customManifest.SkillID, "skill_manifest.json"))
	if err != nil {
		t.Fatalf("load custom manifest: %v", err)
	}
	if kept.Description != customManifest.Description {
		t.Fatalf("custom description should be preserved, got %q", kept.Description)
	}
}

func TestBackfillSkillDescriptionsUpgradesStaleCuratedDescription(t *testing.T) {
	root := t.TempDir()
	archive := skill_step.NewArchiveService(root)
	manifest := &skill_step.SkillManifest{
		SchemaVersion:  skill_step.SchemaManifestV1,
		SkillID:        "go-program-program-2c889620-skill-1781019832374554000",
		DisplayName:    "產出電料Bom",
		Version:        "1.0.0",
		DescriptionDoc: "README.md",
		Description:    "讀取電料BOM與編碼紀錄，交叉比對料號並補齊品名、規格、單價，輸出整合後的電料BOM表；需要輸入：電料BOM、編碼紀錄；資料來源：已載入或匯入的 CSV/XLSX 表格；輸出：整合後電料BOM表",
	}
	if _, err := archive.SavePendingDraft(manifest); err != nil {
		t.Fatalf("save stale curated draft: %v", err)
	}

	app := &App{skillArchive: archive}
	app.backfillSkillDescriptions("test")

	upgraded, err := skill_step.LoadManifest(filepath.Join(root, "data", "skills", manifest.SkillID, "skill_manifest.json"))
	if err != nil {
		t.Fatalf("load upgraded manifest: %v", err)
	}
	for _, want := range []string{"依指定機台", "需要輸入：機台、電料BOM、編碼紀錄"} {
		if !strings.Contains(upgraded.Description, want) {
			t.Fatalf("stale curated description should be upgraded with %q: %s", want, upgraded.Description)
		}
	}
}
