package blackboard

// master.go — 主持人主檔（Host Master）寫出（spec §1、§9）。
// 主檔由持有有效 lease 的 coordinator 投影器整份重寫；它是可再生的
// 索引/摘要，不是原始紀錄，因此重寫不違反 append-only。

import (
	"fmt"
	"strings"
)

// WriteHostMaster atomically rewrites the host master document with the
// current projection. projectedAt is injected by the caller (determinism
// contract, spec §16).
func WriteHostMaster(path string, st MeetingState, projectedBy, projectedAt string) error {
	var b strings.Builder
	b.WriteString("# Blackboard Host Master\n\n")
	b.WriteString("<!-- auto-generated by the coordinator projector; do not edit by hand -->\n\n")
	b.WriteString(RenderMeetingState(st, projectedBy, projectedAt))
	if st.DeadLetterCount > 0 {
		fmt.Fprintf(&b, "> 本機偵測到 %d 筆無法解析事件（詳見本機 dead letter）。\n", st.DeadLetterCount)
	}
	return atomicWrite(path, []byte(b.String()))
}
