// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {statusrail} from '../models';
import {tools} from '../models';
import {main} from '../models';
import {dag} from '../models';
import {skill_step} from '../models';
import {llm_context} from '../models';
import {source_trust} from '../models';
import {voice} from '../models';
import {onboarding} from '../models';
import {credential} from '../models';
import {review} from '../models';
import {scheduler} from '../models';
import {stop_recovery} from '../models';
import {w3a_media} from '../models';
import {visual_learning} from '../models';
import {remote_bridge} from '../models';
import {subexport} from '../models';
import {health} from '../models';
import {persona_avatar} from '../models';
import {settings} from '../models';
import {memory} from '../models';
import {debugtrace} from '../models';
import {browser_pref} from '../models';
import {taborder} from '../models';

export function AcknowledgePendingItem(arg1:string,arg2:string):Promise<void>;

export function AcknowledgePendingItemWithConfirmation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AcknowledgeStatusRail():Promise<statusrail.View>;

export function ActivateRemoteBridgeChannel(arg1:string):Promise<any>;

export function ActivateTool(arg1:string):Promise<tools.ActionResult>;

export function AddActionCandidate(arg1:string,arg2:string,arg3:string):Promise<any>;

export function AddElementDictionaryEntry(arg1:string,arg2:string,arg3:number):Promise<any>;

export function AddSourceToAllowlist(arg1:string):Promise<void>;

export function AddVLReviewCard(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<any>;

export function AddW3ATrustedDeveloper(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AnalyzeSessionForSub():Promise<main.SessionAnalysis>;

export function AppendTabOrder(arg1:string):Promise<void>;

export function AppendTalkEntry(arg1:string,arg2:string):Promise<void>;

export function AppendTalkEntryForAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ApplyUIStyleDiff(arg1:string):Promise<any>;

export function ApproveActionCandidate(arg1:string):Promise<void>;

export function ApproveElementDictionaryEntry(arg1:string):Promise<void>;

export function ApproveTaskStep(arg1:string):Promise<dag.DAGRun>;

export function AutoDetectCLI():Promise<any>;

export function BuildAndSaveSkillDraft(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:skill_step.ExpectedChain):Promise<main.SkillDraftSaveResult>;

export function BuildLLMContext(arg1:string,arg2:string,arg3:boolean):Promise<llm_context.ContextPayload>;

export function BuildSkillContext(arg1:string,arg2:string):Promise<skill_step.Injection>;

export function BuildSkillDraft(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:skill_step.ExpectedChain):Promise<skill_step.SkillManifest|Array<string>>;

export function CancelActiveTaskProgress(arg1:string):Promise<dag.DAGRun>;

export function CancelChatMessage(arg1:string):Promise<void>;

export function CancelPreview():Promise<any>;

export function CancelScheduledJob(arg1:string):Promise<void>;

export function CancelTaskProgress(arg1:string,arg2:string):Promise<dag.DAGRun>;

export function ClassifySource(arg1:string,arg2:string,arg3:Array<string>):Promise<source_trust.SourceTrustEvidence>;

export function CleanOrphanQuarantine(arg1:string):Promise<void>;

export function CleanupEphemeralProfiles():Promise<void>;

export function ClearInspectorHistory():Promise<void>;

export function ClearMainTalk():Promise<void>;

export function ClearSessionImages(arg1:string):Promise<void>;

export function ClearSkillContext(arg1:string,arg2:string):Promise<void>;

export function ClearVoiceDebug():Promise<voice.State>;

export function ClearWebSearchConfig():Promise<any>;

export function CommitPreview():Promise<any>;

export function CompleteOnboardingStep(arg1:string):Promise<onboarding.State>;

export function ComputeDryRunConfidence(arg1:number,arg2:number,arg3:number):Promise<number>;

export function ConfirmAndExecuteSkillExecution(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.SkillExecutionDecision>;

export function ConfirmClose(arg1:boolean,arg2:string):Promise<void>;

export function ConfirmCredentialMigration():Promise<credential.MigrationStatus>;

export function ConfirmPackageInstall(arg1:string):Promise<void>;

export function ConfirmRegisterLLMAPIAdapter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<any>;

export function ConfirmSkillArchive(arg1:string):Promise<any>;

export function ConfirmSkillExecution(arg1:string,arg2:string,arg3:string):Promise<main.SkillExecutionDecision>;

export function ConfirmTelegramChatID(arg1:string,arg2:string):Promise<void>;

export function CreateDAGRun(arg1:string,arg2:string):Promise<dag.DAGRun>;

export function CreateDestructiveReviewCard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<review.Card>;

export function CreateScheduledJob(arg1:string,arg2:string,arg3:string,arg4:string):Promise<scheduler.Job>;

export function CreateStopRecoveryCard(arg1:string,arg2:string):Promise<stop_recovery.StopRecoveryCard>;

export function CreateSubagent(arg1:string):Promise<main.CreatedSubagent>;

export function DeactivateRemoteBridgeChannel(arg1:string):Promise<void>;

export function DeleteAvatarCredential(arg1:string):Promise<void>;

export function DeleteLearningRun(arg1:string):Promise<void>;

export function DeleteScheduledJob(arg1:string):Promise<void>;

export function DeleteStaticAvatar(arg1:string):Promise<void>;

export function DeleteTalkMessageForAgent(arg1:string,arg2:string):Promise<boolean>;

export function DetectModelPollution(arg1:string):Promise<w3a_media.PollutionReport>;

export function DetectOllamaState():Promise<main.OllamaState>;

export function DetectRegions(arg1:Array<number>,arg2:number,arg3:number):Promise<visual_learning.DetectorResult>;

export function DetectRemoteBridgeChannel(arg1:string):Promise<remote_bridge.DetectResult>;

export function DisableContextualRiskOverride(arg1:string):Promise<void>;

export function DisableCredentialMigration():Promise<credential.MigrationStatus>;

export function DismissEmbeddingPicker():Promise<void>;

export function DismissFloatingCandidates():Promise<void>;

export function DismissSummarization():Promise<void>;

export function DispatchRemoteBridgeAsync(arg1:string,arg2:string):Promise<string>;

export function DualStepConfirmStep1(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EnableContextualRiskOverride(arg1:string,arg2:string):Promise<string>;

export function EnableDetectedCLI(arg1:string):Promise<void>;

export function EnableLocalModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function EnableTrustedSessionScope(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EnableWorkflowTrustForHours(arg1:string,arg2:string,arg3:number):Promise<string>;

export function EnterDegradedMode(arg1:string):Promise<any>;

export function EscapeExternalTokens(arg1:string):Promise<string>;

export function ExecuteNativeLearningReplayStep(arg1:string):Promise<any>;

export function ExecuteResolvedSkill(arg1:string,arg2:string):Promise<main.SkillExecutionDecision>;

export function ExecuteSkillMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SkillExecutionDecision>;

export function ExitDegradedMode():Promise<any>;

export function ExportDocumentToPath(arg1:string):Promise<string>;

export function ExportMediaWithSidecar(arg1:string,arg2:string):Promise<void>;

export function ExportPersonaHandler(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ExportProjectBackupHandler(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<Record<string, any>>;

export function ExportSubHandler(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<subexport.ExportResult>;

export function ExportVisualLearning(arg1:string):Promise<any>;

export function FetchURLContent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<any>;

export function FinalizeNativeGoProgramAuthoringExport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FinalizeNativeLearningRunExport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FinalizeNativePersonaExport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function FinalizeNativeReferenceFileExport(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FinalizeNativeSkillExport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function FinalizeNativeSubExport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function FinishOnboarding():Promise<void>;

export function GenerateLearningRunMetadata(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function GetActiveLearningRun():Promise<any>;

export function GetAdapterModelChoices():Promise<Record<string, string>>;

export function GetAdapterStatus(arg1:string):Promise<any>;

export function GetAppSessionID():Promise<string>;

export function GetAvatarStateTrigger(arg1:string,arg2:string):Promise<string>;

export function GetBrowserPreference():Promise<any>;

export function GetCanonicalLabelSchema():Promise<Array<visual_learning.CanonicalLabel>>;

export function GetConfigPublic():Promise<health.ConfigPublic>;

export function GetConsoleState():Promise<main.ConsoleState>;

export function GetCredentialMigrationStatus():Promise<credential.MigrationStatus>;

export function GetCurrentAvatar(arg1:string):Promise<persona_avatar.AvatarConfig>;

export function GetDAGRun(arg1:string):Promise<dag.DAGRun>;

export function GetDAGRunDebug(arg1:string):Promise<any>;

export function GetDegradedState():Promise<any>;

export function GetDeviceTrustProfile(arg1:string):Promise<any>;

export function GetEmbeddingConfig():Promise<settings.EmbeddingConfig>;

export function GetGoProgramAuthoringDetail(arg1:string):Promise<main.GoProgramAuthoringDetail>;

export function GetHighImpactDomains():Promise<Array<string>>;

export function GetHookGeneReviewSummary(arg1:string):Promise<main.HookGeneReviewSummary>;

export function GetHookSummary(arg1:string):Promise<any>;

export function GetJobExecutionHistory(arg1:string,arg2:number):Promise<Array<scheduler.JobExecution>>;

export function GetLastLearningReplayPlan():Promise<any>;

export function GetLearningReplayPlan(arg1:string):Promise<any>;

export function GetMediaW3AInfo(arg1:string):Promise<any>;

export function GetMemoryHealth():Promise<health.MemoryHealth>;

export function GetMemoryPipelineState():Promise<memory.PipelineState>;

export function GetMonitorLinks():Promise<debugtrace.LinkSnapshot>;

export function GetNativeOCRStatus():Promise<visual_learning.OCRStatus>;

export function GetNewSubagentCandidates():Promise<any>;

export function GetOnboardingState():Promise<onboarding.State>;

export function GetOpenCVStatus():Promise<boolean>;

export function GetPendingCandidateCount():Promise<number>;

export function GetPendingDigest():Promise<any>;

export function GetPendingTagPatches():Promise<any>;

export function GetPixelAvatarPack():Promise<string>;

export function GetPixelAvatarPath(arg1:string,arg2:number):Promise<string>;

export function GetProjectAllowlist():Promise<any>;

export function GetReadinessGateState():Promise<main.ReadinessGateState>;

export function GetRecentSkillInjections(arg1:string):Promise<any>;

export function GetRemoteBridgeAudit(arg1:number):Promise<any>;

export function GetRemoteBridgeInboundEndpoint(arg1:string):Promise<any>;

export function GetReviewExecutionContext(arg1:string):Promise<review.ReviewExecutionContext>;

export function GetSafariRuntimeNotice():Promise<browser_pref.RuntimeNoticeResult>;

export function GetSettingsState():Promise<settings.State>;

export function GetSidecarState():Promise<string>;

export function GetStopRecoveryCard(arg1:string):Promise<stop_recovery.StopRecoveryCard>;

export function GetSubExportCapabilities():Promise<main.SubExportCapabilities>;

export function GetSubExportDesktopDirectory():Promise<string>;

export function GetSubExportFallbackDirectory():Promise<string>;

export function GetSummaryModelSettings():Promise<settings.SummaryModelSettings>;

export function GetTTSPackStatus():Promise<voice.TTSPackStatus>;

export function GetTabOrder():Promise<taborder.TabOrder>;

export function GetTalkMessagesForAgent(arg1:string):Promise<Array<string>>;

export function GetToolRegistryPatchProposals():Promise<any>;

export function GetToolVisibility():Promise<any>;

export function GetUISettings():Promise<any>;

export function GetURLProvenance(arg1:string):Promise<any>;

export function GetVoiceSettings():Promise<voice.State>;

export function GetW3ATransferGuidance():Promise<w3a_media.TransferGuidance>;

export function GetWebSearchConfig():Promise<any>;

export function GetYOLODetailedStatus():Promise<visual_learning.InferenceStatus>;

export function GetYOLOStatus():Promise<boolean>;

export function GoBackOnboarding():Promise<onboarding.State>;

export function HandleDocumentDrop(arg1:string):Promise<main.DocumentImportResult>;

export function HasAvatarCredential(arg1:string):Promise<boolean>;

export function HasBlockingReviewCard():Promise<boolean>;

export function HasBlockingVLReview():Promise<boolean>;

export function HasOpenStopRecoveryCard():Promise<boolean>;

export function ImportGoProgramExport(arg1:string):Promise<main.GoProgramAuthoringCatalogItem>;

export function ImportLearningRunExport(arg1:string):Promise<main.LearningRunExportPreview>;

export function ImportMediaVerify(arg1:string):Promise<any>;

export function ImportProjectBackupHandler(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ImportReferenceFile(arg1:string):Promise<main.ReferenceFile>;

export function ImportSubHandler(arg1:string):Promise<main.ImportSubResult>;

export function ImportVideoFile(arg1:string):Promise<main.ReferenceFile>;

export function InspectProjectBackupHandler(arg1:string,arg2:string):Promise<Record<string, any>>;

export function InstallTTSPack():Promise<voice.TTSPackStatus>;

export function InstallVoiceBaseModel():Promise<voice.State>;

export function InvalidateDualStep(arg1:string):Promise<void>;

export function IsDegradedBlocked(arg1:string):Promise<boolean>;

export function IsDocumentFormat(arg1:string):Promise<boolean>;

export function IsLearningModeActive():Promise<boolean>;

export function IsLivePreviewActive():Promise<boolean>;

export function IsProjectBackupEncryptedHandler(arg1:string):Promise<Record<string, any>>;

export function IsReadOnlyMode():Promise<boolean>;

export function ListAdapterModelOptions(arg1:string):Promise<Array<string>>;

export function ListArchivedSkills():Promise<any>;

export function ListAvailableAdapters():Promise<any>;

export function ListAvatarPresets():Promise<Array<persona_avatar.StylePreset>>;

export function ListDAGRuns():Promise<Array<dag.DAGRun>>;

export function ListDAGRunsFromIndex(arg1:number,arg2:string):Promise<Array<dag.DAGRunSummary>>;

export function ListElementDictionary(arg1:string):Promise<any>;

export function ListExternalLinksByType(arg1:string):Promise<any>;

export function ListFormalActions():Promise<any>;

export function ListGoProgramAuthoringCatalog(arg1:number):Promise<Array<main.GoProgramAuthoringCatalogItem>>;

export function ListInstalledEmbedModels():Promise<Array<main.EmbedModelInfo>>;

export function ListLLMProviderWhitelist():Promise<any>;

export function ListLearningReplayCatalog(arg1:number):Promise<any>;

export function ListOpenLightweightCards():Promise<Array<review.LightweightCard>>;

export function ListOpenReviewCards():Promise<Array<review.Card>>;

export function ListOpenStopRecoveryCards():Promise<Array<stop_recovery.StopRecoveryCard>>;

export function ListOpenVLReviewCards():Promise<any>;

export function ListPendingActions():Promise<any>;

export function ListPendingCandidates():Promise<any>;

export function ListPendingPackages():Promise<any>;

export function ListPixelAvatarPacks():Promise<Array<Record<string, string>>>;

export function ListProjectDocuments():Promise<any>;

export function ListPurgeManifests():Promise<any>;

export function ListReferenceFiles():Promise<Array<main.ReferenceFile>>;

export function ListReferenceImages():Promise<Array<main.ReferenceFile>>;

export function ListRemoteBridgeChannels():Promise<any>;

export function ListRemoteBridgeInboundAdapters():Promise<any>;

export function ListRemoteBridgePresets():Promise<any>;

export function ListReviewArchive():Promise<Array<review.ArchivedCard>>;

export function ListScheduledJobs():Promise<Array<scheduler.Job>>;

export function ListThreatRecords():Promise<any>;

export function ListTools():Promise<Array<tools.Tool>>;

export function ListVideoFiles():Promise<Array<main.ReferenceFile>>;

export function ListW3ATrustedDevelopers():Promise<any>;

export function MapCanonicalLabel(arg1:string,arg2:string,arg3:number):Promise<visual_learning.CanonicalLabel|boolean>;

export function MarkSkillFirstUseExplained():Promise<any>;

export function MarkToolAvailable(arg1:string):Promise<void>;

export function MarkToolUnavailable(arg1:string,arg2:string):Promise<void>;

export function NativeDragExportGoProgramAuthoring(arg1:string):Promise<main.NativeGoProgramDragExportResult>;

export function NativeDragExportLearningRun(arg1:string):Promise<main.NativeLearningRunDragExportResult>;

export function NativeDragExportPersonaHandler(arg1:string,arg2:string):Promise<main.NativePersonaDragExportResult>;

export function NativeDragExportReferenceFile(arg1:string):Promise<main.NativeReferenceFileDragResult>;

export function NativeDragExportSkill(arg1:string):Promise<main.NativeSkillDragExportResult>;

export function NativeDragExportSubHandler(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.NativeSubDragExportResult>;

export function NextGreeting(arg1:string):Promise<string>;

export function NotifyStatusRail(arg1:string,arg2:string,arg3:string,arg4:string):Promise<statusrail.View>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function PauseScheduledJob(arg1:string):Promise<void>;

export function PollStatusRail():Promise<statusrail.View>;

export function PollTelegramChatID(arg1:string):Promise<any>;

export function PrepareAvatarGenerateRequest(arg1:string,arg2:string):Promise<persona_avatar.GenerateAvatarRequest>;

export function PrepareCloudTTSText(arg1:string):Promise<voice.CloudTTSEgressPreview>;

export function PreparePackageInstall(arg1:string,arg2:string):Promise<any>;

export function PreparePackageInstallPayload(arg1:string,arg2:string,arg3:string):Promise<any>;

export function PreviewExternalLink(arg1:string):Promise<any>;

export function PreviewGoProgramExport(arg1:string):Promise<main.GoProgramExportPreview>;

export function PreviewLearningRunExport(arg1:string):Promise<main.LearningRunExportPreview>;

export function PreviewSubPackage(arg1:string):Promise<main.SubPackagePreview>;

export function PromoteDraftToPending(arg1:string,arg2:string):Promise<string>;

export function ProposeRegions(arg1:Array<number>,arg2:number,arg3:number):Promise<any>;

export function PullEmbedModel(arg1:string):Promise<main.EmbedPullJob>;

export function PurgeBoundaryDir(arg1:string):Promise<void>;

export function PurgeProject(arg1:string,arg2:string):Promise<any>;

export function ReadDocumentContent(arg1:string):Promise<string>;

export function RecognizeNativeOCR(arg1:Array<number>):Promise<Array<visual_learning.OCRResult>>;

export function RecordLearningMouseEvent(arg1:string):Promise<void>;

export function RecordMainInteraction(arg1:string,arg2:string):Promise<statusrail.View>;

export function RecordStepTrace(arg1:string,arg2:string):Promise<void>;

export function RefreshPendingCandidateAges():Promise<void>;

export function RegisterCustomCLI(arg1:string,arg2:string):Promise<any>;

export function RegisterExternalLink(arg1:string,arg2:string):Promise<any>;

export function RegisterLLMAPIAdapter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<any>;

export function RegisterRemoteBridgeChannel(arg1:string):Promise<any>;

export function RegisterRemoteBridgeChannelWithMode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function RegisterSchedulerCallback(arg1:string):Promise<void>;

export function RegisterURLOccurrence(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function RejectPackageInstall(arg1:string,arg2:string):Promise<void>;

export function RemoveAllowlistEntry(arg1:string):Promise<void>;

export function RemoveRemoteBridgeChannel(arg1:string):Promise<void>;

export function RemoveTTSPack():Promise<voice.TTSPackStatus>;

export function RemoveTabOrder(arg1:string):Promise<void>;

export function RemoveVoiceBaseModel():Promise<voice.State>;

export function RenameAdapter(arg1:string,arg2:string):Promise<any>;

export function RenameRemoteBridgeChannel(arg1:string,arg2:string):Promise<any>;

export function RenameSubagent(arg1:string,arg2:string):Promise<main.CreatedSubagent>;

export function RenderPixelAvatar(arg1:string,arg2:number):Promise<Array<number>>;

export function RenderPixelAvatarPreview(arg1:string,arg2:string,arg3:number):Promise<Array<number>>;

export function RenewAllowlistEntry(arg1:string):Promise<void>;

export function ReorderAdapters(arg1:string):Promise<void>;

export function ReorderPersonas(arg1:Array<string>):Promise<settings.State>;

export function ReorderTabs(arg1:string):Promise<void>;

export function ResolveAndExecuteDestructiveReviewCard(arg1:string,arg2:string):Promise<main.DestructiveReviewExecutionResult>;

export function ResolveImportToolConflict(arg1:string):Promise<void>;

export function ResolveImportToolConflicts(arg1:string):Promise<void>;

export function ResolveLightweightCard(arg1:string):Promise<void>;

export function ResolveReviewCard(arg1:string):Promise<void>;

export function ResolveSkillForAction(arg1:string,arg2:string):Promise<skill_step.ResolveResult>;

export function ResolveStopRecoveryCard(arg1:string,arg2:string):Promise<void>;

export function ResolveVLReviewCard(arg1:string):Promise<void>;

export function ResolveWindowsClickAnchor(arg1:Array<number>,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<visual_learning.WindowsClickAnchorResult>;

export function RestartSidecar():Promise<void>;

export function RestoreUIDefaults():Promise<any>;

export function ResumeDAGRun(arg1:string):Promise<dag.GuardCheckResult>;

export function ResumeScheduledJob(arg1:string):Promise<void>;

export function RetryRemoteBridgeSegment(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RotateTalkFull():Promise<string>;

export function RouteVoiceCommand(arg1:string):Promise<voice.CommandRoute>;

export function RunGoProgramAuthoringLoop(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.GoProgramAuthoringResult>;

export function RunPackageSecurityCheck(arg1:string):Promise<any>;

export function RunSummarizationNow(arg1:string):Promise<string>;

export function SaveDocumentFromAgent(arg1:string,arg2:string,arg3:string):Promise<main.DocumentPreview>;

export function SaveMainAsSub(arg1:string):Promise<string>;

export function SavePanelSettings(arg1:settings.PanelSettings):Promise<settings.State>;

export function SavePersona(arg1:settings.Persona):Promise<settings.State>;

export function SaveRemoteBridgeInboundSecret(arg1:string,arg2:string):Promise<void>;

export function SaveStaticAvatar(arg1:string,arg2:Array<number>,arg3:string,arg4:string):Promise<void>;

export function SaveSummaryModelSettings(arg1:settings.SummaryModelSettings):Promise<settings.SummaryModelSettings>;

export function SaveVoiceSettings(arg1:voice.Settings):Promise<voice.State>;

export function SaveWebSearchConfig(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ScanLocalModels():Promise<any>;

export function ScanLocalSummaryModels():Promise<main.SummaryModelScanResult>;

export function ScanOrphanQuarantine():Promise<any>;

export function ScanSkillFolder(arg1:string):Promise<any>;

export function SearchLearningOperations(arg1:string,arg2:number):Promise<any>;

export function SearchWeb(arg1:string,arg2:number):Promise<any>;

export function SearchWebConfirmed(arg1:string,arg2:number):Promise<any>;

export function SelectFloatingCandidate(arg1:string):Promise<main.ReadinessGateState>;

export function SelectPersonaExportDirectory():Promise<string>;

export function SelectProjectBackupExportDirectory():Promise<string>;

export function SelectProjectBackupFile():Promise<string>;

export function SelectSubExportDirectory():Promise<string>;

export function SendAPIMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skill_step.CLIResponse>;

export function SendCLIMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skill_step.CLIResponse>;

export function SendInspectorAPIMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skill_step.CLIResponse>;

export function SendInspectorMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skill_step.CLIResponse>;

export function SendTopInteractionMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<skill_step.CLIResponse>;

export function SetActiveConversationAgent(arg1:string):Promise<void>;

export function SetAdapterModelChoice(arg1:string,arg2:string):Promise<void>;

export function SetAdapterStatus(arg1:string,arg2:string):Promise<void>;

export function SetAvatarProvider(arg1:string,arg2:string):Promise<void>;

export function SetBrowserPreference(arg1:string,arg2:string):Promise<browser_pref.RuntimeNoticeResult>;

export function SetEmbeddingConfig(arg1:string,arg2:string):Promise<void>;

export function SetPersonaPixelAvatarPack(arg1:string,arg2:string):Promise<void>;

export function SetPixelAvatarPack(arg1:string):Promise<void>;

export function SetRemoteBridgePrimaryChannel(arg1:string):Promise<any>;

export function SetToolPreference(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SetTrustDomAndClick(arg1:boolean):Promise<void>;

export function StageSessionImages(arg1:string,arg2:Array<string>):Promise<number>;

export function StartDraftSandbox(arg1:string):Promise<string>;

export function StartGoProgramAuthoring(arg1:string,arg2:string,arg3:string):Promise<main.GoProgramAuthoringResult>;

export function StartHookRun(arg1:string,arg2:string):Promise<string>;

export function StartLearningMode(arg1:string):Promise<any>;

export function StartLivePreview(arg1:string):Promise<any>;

export function StartTaskProgress(arg1:string,arg2:string,arg3:string,arg4:string):Promise<dag.DAGRun>;

export function StartTelegramOnboarding(arg1:string):Promise<any>;

export function StartURLVisualLearning(arg1:string,arg2:string,arg3:string):Promise<any>;

export function StopDraftSandbox(arg1:string,arg2:string):Promise<void>;

export function StopLearningMode():Promise<any>;

export function StopSidecar():Promise<void>;

export function StopURLVisualLearning():Promise<any>;

export function StoreAvatarCredential(arg1:string,arg2:string):Promise<void>;

export function SubmitTaskLoopInput(arg1:string,arg2:string,arg3:string):Promise<dag.DAGRun>;

export function SwitchRemoteBridgeMode(arg1:string,arg2:string):Promise<any>;

export function TestRemoteBridgeConnection(arg1:string):Promise<any>;

export function TranscribeVoiceWAV(arg1:string,arg2:string):Promise<voice.TranscriptResult>;

export function UnregisterAdapter(arg1:string):Promise<void>;

export function UpdateDAGNodeStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLearningRunMetadata(arg1:string):Promise<any>;

export function ValidateMemoryItem(arg1:string):Promise<memory.ValidationResult>;

export function VerifyMediaFile(arg1:string):Promise<any>;

export function WakeLocalAdapter(arg1:string):Promise<any>;

export function WakeOllamaDaemon():Promise<void>;
