// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgePendingItem(arg1, arg2) {
  return window['go']['main']['App']['AcknowledgePendingItem'](arg1, arg2);
}

export function AcknowledgePendingItemWithConfirmation(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcknowledgePendingItemWithConfirmation'](arg1, arg2, arg3);
}

export function AcknowledgeStatusRail() {
  return window['go']['main']['App']['AcknowledgeStatusRail']();
}

export function ActivateRemoteBridgeChannel(arg1) {
  return window['go']['main']['App']['ActivateRemoteBridgeChannel'](arg1);
}

export function ActivateTool(arg1) {
  return window['go']['main']['App']['ActivateTool'](arg1);
}

export function AddActionCandidate(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddActionCandidate'](arg1, arg2, arg3);
}

export function AddElementDictionaryEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddElementDictionaryEntry'](arg1, arg2, arg3);
}

export function AddSourceToAllowlist(arg1) {
  return window['go']['main']['App']['AddSourceToAllowlist'](arg1);
}

export function AddVLReviewCard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddVLReviewCard'](arg1, arg2, arg3, arg4, arg5);
}

export function AddW3ATrustedDeveloper(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddW3ATrustedDeveloper'](arg1, arg2, arg3);
}

export function AnalyzeSessionForSub() {
  return window['go']['main']['App']['AnalyzeSessionForSub']();
}

export function AppendTabOrder(arg1) {
  return window['go']['main']['App']['AppendTabOrder'](arg1);
}

export function AppendTalkEntry(arg1, arg2) {
  return window['go']['main']['App']['AppendTalkEntry'](arg1, arg2);
}

export function AppendTalkEntryForAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendTalkEntryForAgent'](arg1, arg2, arg3);
}

export function ApplyUIStyleDiff(arg1) {
  return window['go']['main']['App']['ApplyUIStyleDiff'](arg1);
}

export function ApproveActionCandidate(arg1) {
  return window['go']['main']['App']['ApproveActionCandidate'](arg1);
}

export function ApproveElementDictionaryEntry(arg1) {
  return window['go']['main']['App']['ApproveElementDictionaryEntry'](arg1);
}

export function ApproveTaskStep(arg1) {
  return window['go']['main']['App']['ApproveTaskStep'](arg1);
}

export function AutoDetectCLI() {
  return window['go']['main']['App']['AutoDetectCLI']();
}

export function BuildAndSaveSkillDraft(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildAndSaveSkillDraft'](arg1, arg2, arg3, arg4, arg5);
}

export function BuildLLMContext(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildLLMContext'](arg1, arg2, arg3);
}

export function BuildSkillContext(arg1, arg2) {
  return window['go']['main']['App']['BuildSkillContext'](arg1, arg2);
}

export function BuildSkillDraft(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildSkillDraft'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelActiveTaskProgress(arg1) {
  return window['go']['main']['App']['CancelActiveTaskProgress'](arg1);
}

export function CancelChatMessage(arg1) {
  return window['go']['main']['App']['CancelChatMessage'](arg1);
}

export function CancelPreview() {
  return window['go']['main']['App']['CancelPreview']();
}

export function CancelScheduledJob(arg1) {
  return window['go']['main']['App']['CancelScheduledJob'](arg1);
}

export function CancelTaskProgress(arg1, arg2) {
  return window['go']['main']['App']['CancelTaskProgress'](arg1, arg2);
}

export function ClassifySource(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClassifySource'](arg1, arg2, arg3);
}

export function CleanOrphanQuarantine(arg1) {
  return window['go']['main']['App']['CleanOrphanQuarantine'](arg1);
}

export function CleanupEphemeralProfiles() {
  return window['go']['main']['App']['CleanupEphemeralProfiles']();
}

export function ClearInspectorHistory() {
  return window['go']['main']['App']['ClearInspectorHistory']();
}

export function ClearMainTalk() {
  return window['go']['main']['App']['ClearMainTalk']();
}

export function ClearSessionImages(arg1) {
  return window['go']['main']['App']['ClearSessionImages'](arg1);
}

export function ClearSkillContext(arg1, arg2) {
  return window['go']['main']['App']['ClearSkillContext'](arg1, arg2);
}

export function ClearVoiceDebug() {
  return window['go']['main']['App']['ClearVoiceDebug']();
}

export function ClearWebSearchConfig() {
  return window['go']['main']['App']['ClearWebSearchConfig']();
}

export function CommitPreview() {
  return window['go']['main']['App']['CommitPreview']();
}

export function CompleteOnboardingStep(arg1) {
  return window['go']['main']['App']['CompleteOnboardingStep'](arg1);
}

export function ComputeDryRunConfidence(arg1, arg2, arg3) {
  return window['go']['main']['App']['ComputeDryRunConfidence'](arg1, arg2, arg3);
}

export function ConfirmAndExecuteSkillExecution(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ConfirmAndExecuteSkillExecution'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ConfirmClose(arg1, arg2) {
  return window['go']['main']['App']['ConfirmClose'](arg1, arg2);
}

export function ConfirmCredentialMigration() {
  return window['go']['main']['App']['ConfirmCredentialMigration']();
}

export function ConfirmPackageInstall(arg1) {
  return window['go']['main']['App']['ConfirmPackageInstall'](arg1);
}

export function ConfirmRegisterLLMAPIAdapter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConfirmRegisterLLMAPIAdapter'](arg1, arg2, arg3, arg4, arg5);
}

export function ConfirmSkillArchive(arg1) {
  return window['go']['main']['App']['ConfirmSkillArchive'](arg1);
}

export function ConfirmSkillExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmSkillExecution'](arg1, arg2, arg3);
}

export function ConfirmTelegramChatID(arg1, arg2) {
  return window['go']['main']['App']['ConfirmTelegramChatID'](arg1, arg2);
}

export function CreateDAGRun(arg1, arg2) {
  return window['go']['main']['App']['CreateDAGRun'](arg1, arg2);
}

export function CreateDestructiveReviewCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDestructiveReviewCard'](arg1, arg2, arg3, arg4);
}

export function CreateScheduledJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateScheduledJob'](arg1, arg2, arg3, arg4);
}

export function CreateStopRecoveryCard(arg1, arg2) {
  return window['go']['main']['App']['CreateStopRecoveryCard'](arg1, arg2);
}

export function CreateSubagent(arg1) {
  return window['go']['main']['App']['CreateSubagent'](arg1);
}

export function DeactivateRemoteBridgeChannel(arg1) {
  return window['go']['main']['App']['DeactivateRemoteBridgeChannel'](arg1);
}

export function DeleteAvatarCredential(arg1) {
  return window['go']['main']['App']['DeleteAvatarCredential'](arg1);
}

export function DeleteLearningRun(arg1) {
  return window['go']['main']['App']['DeleteLearningRun'](arg1);
}

export function DeleteScheduledJob(arg1) {
  return window['go']['main']['App']['DeleteScheduledJob'](arg1);
}

export function DeleteStaticAvatar(arg1) {
  return window['go']['main']['App']['DeleteStaticAvatar'](arg1);
}

export function DeleteTalkMessageForAgent(arg1, arg2) {
  return window['go']['main']['App']['DeleteTalkMessageForAgent'](arg1, arg2);
}

export function DetectModelPollution(arg1) {
  return window['go']['main']['App']['DetectModelPollution'](arg1);
}

export function DetectOllamaState() {
  return window['go']['main']['App']['DetectOllamaState']();
}

export function DetectRegions(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectRegions'](arg1, arg2, arg3);
}

export function DetectRemoteBridgeChannel(arg1) {
  return window['go']['main']['App']['DetectRemoteBridgeChannel'](arg1);
}

export function DisableContextualRiskOverride(arg1) {
  return window['go']['main']['App']['DisableContextualRiskOverride'](arg1);
}

export function DisableCredentialMigration() {
  return window['go']['main']['App']['DisableCredentialMigration']();
}

export function DismissEmbeddingPicker() {
  return window['go']['main']['App']['DismissEmbeddingPicker']();
}

export function DismissFloatingCandidates() {
  return window['go']['main']['App']['DismissFloatingCandidates']();
}

export function DismissSummarization() {
  return window['go']['main']['App']['DismissSummarization']();
}

export function DispatchRemoteBridgeAsync(arg1, arg2) {
  return window['go']['main']['App']['DispatchRemoteBridgeAsync'](arg1, arg2);
}

export function DualStepConfirmStep1(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DualStepConfirmStep1'](arg1, arg2, arg3, arg4);
}

export function EnableContextualRiskOverride(arg1, arg2) {
  return window['go']['main']['App']['EnableContextualRiskOverride'](arg1, arg2);
}

export function EnableDetectedCLI(arg1) {
  return window['go']['main']['App']['EnableDetectedCLI'](arg1);
}

export function EnableLocalModel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EnableLocalModel'](arg1, arg2, arg3, arg4, arg5);
}

export function EnableTrustedSessionScope(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EnableTrustedSessionScope'](arg1, arg2, arg3, arg4);
}

export function EnableWorkflowTrustForHours(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnableWorkflowTrustForHours'](arg1, arg2, arg3);
}

export function EnterDegradedMode(arg1) {
  return window['go']['main']['App']['EnterDegradedMode'](arg1);
}

export function EscapeExternalTokens(arg1) {
  return window['go']['main']['App']['EscapeExternalTokens'](arg1);
}

export function ExecuteNativeLearningReplayStep(arg1) {
  return window['go']['main']['App']['ExecuteNativeLearningReplayStep'](arg1);
}

export function ExecuteResolvedSkill(arg1, arg2) {
  return window['go']['main']['App']['ExecuteResolvedSkill'](arg1, arg2);
}

export function ExecuteSkillMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteSkillMessage'](arg1, arg2, arg3, arg4);
}

export function ExitDegradedMode() {
  return window['go']['main']['App']['ExitDegradedMode']();
}

export function ExportDocumentToPath(arg1) {
  return window['go']['main']['App']['ExportDocumentToPath'](arg1);
}

export function ExportMediaWithSidecar(arg1, arg2) {
  return window['go']['main']['App']['ExportMediaWithSidecar'](arg1, arg2);
}

export function ExportPersonaHandler(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportPersonaHandler'](arg1, arg2, arg3);
}

export function ExportProjectBackupHandler(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportProjectBackupHandler'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportSubHandler(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportSubHandler'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportVisualLearning(arg1) {
  return window['go']['main']['App']['ExportVisualLearning'](arg1);
}

export function FetchURLContent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['FetchURLContent'](arg1, arg2, arg3, arg4, arg5);
}

export function FinalizeNativeGoProgramAuthoringExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FinalizeNativeGoProgramAuthoringExport'](arg1, arg2, arg3, arg4);
}

export function FinalizeNativeLearningRunExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FinalizeNativeLearningRunExport'](arg1, arg2, arg3, arg4);
}

export function FinalizeNativePersonaExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FinalizeNativePersonaExport'](arg1, arg2, arg3, arg4);
}

export function FinalizeNativeReferenceFileExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['FinalizeNativeReferenceFileExport'](arg1, arg2, arg3);
}

export function FinalizeNativeSkillExport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FinalizeNativeSkillExport'](arg1, arg2, arg3, arg4);
}

export function FinalizeNativeSubExport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['FinalizeNativeSubExport'](arg1, arg2, arg3, arg4, arg5);
}

export function FinishOnboarding() {
  return window['go']['main']['App']['FinishOnboarding']();
}

export function GenerateLearningRunMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateLearningRunMetadata'](arg1, arg2, arg3, arg4);
}

export function GetActiveLearningRun() {
  return window['go']['main']['App']['GetActiveLearningRun']();
}

export function GetAdapterModelChoices() {
  return window['go']['main']['App']['GetAdapterModelChoices']();
}

export function GetAdapterStatus(arg1) {
  return window['go']['main']['App']['GetAdapterStatus'](arg1);
}

export function GetAppSessionID() {
  return window['go']['main']['App']['GetAppSessionID']();
}

export function GetAvatarStateTrigger(arg1, arg2) {
  return window['go']['main']['App']['GetAvatarStateTrigger'](arg1, arg2);
}

export function GetBrowserPreference() {
  return window['go']['main']['App']['GetBrowserPreference']();
}

export function GetCanonicalLabelSchema() {
  return window['go']['main']['App']['GetCanonicalLabelSchema']();
}

export function GetConfigPublic() {
  return window['go']['main']['App']['GetConfigPublic']();
}

export function GetConsoleState() {
  return window['go']['main']['App']['GetConsoleState']();
}

export function GetCredentialMigrationStatus() {
  return window['go']['main']['App']['GetCredentialMigrationStatus']();
}

export function GetCurrentAvatar(arg1) {
  return window['go']['main']['App']['GetCurrentAvatar'](arg1);
}

export function GetDAGRun(arg1) {
  return window['go']['main']['App']['GetDAGRun'](arg1);
}

export function GetDAGRunDebug(arg1) {
  return window['go']['main']['App']['GetDAGRunDebug'](arg1);
}

export function GetDegradedState() {
  return window['go']['main']['App']['GetDegradedState']();
}

export function GetDeviceTrustProfile(arg1) {
  return window['go']['main']['App']['GetDeviceTrustProfile'](arg1);
}

export function GetEmbeddingConfig() {
  return window['go']['main']['App']['GetEmbeddingConfig']();
}

export function GetGoProgramAuthoringDetail(arg1) {
  return window['go']['main']['App']['GetGoProgramAuthoringDetail'](arg1);
}

export function GetHighImpactDomains() {
  return window['go']['main']['App']['GetHighImpactDomains']();
}

export function GetHookGeneReviewSummary(arg1) {
  return window['go']['main']['App']['GetHookGeneReviewSummary'](arg1);
}

export function GetHookSummary(arg1) {
  return window['go']['main']['App']['GetHookSummary'](arg1);
}

export function GetJobExecutionHistory(arg1, arg2) {
  return window['go']['main']['App']['GetJobExecutionHistory'](arg1, arg2);
}

export function GetLastLearningReplayPlan() {
  return window['go']['main']['App']['GetLastLearningReplayPlan']();
}

export function GetLearningReplayPlan(arg1) {
  return window['go']['main']['App']['GetLearningReplayPlan'](arg1);
}

export function GetMediaW3AInfo(arg1) {
  return window['go']['main']['App']['GetMediaW3AInfo'](arg1);
}

export function GetMemoryHealth() {
  return window['go']['main']['App']['GetMemoryHealth']();
}

export function GetMemoryPipelineState() {
  return window['go']['main']['App']['GetMemoryPipelineState']();
}

export function GetMonitorLinks() {
  return window['go']['main']['App']['GetMonitorLinks']();
}

export function GetNativeOCRStatus() {
  return window['go']['main']['App']['GetNativeOCRStatus']();
}

export function GetNewSubagentCandidates() {
  return window['go']['main']['App']['GetNewSubagentCandidates']();
}

export function GetOnboardingState() {
  return window['go']['main']['App']['GetOnboardingState']();
}

export function GetOpenCVStatus() {
  return window['go']['main']['App']['GetOpenCVStatus']();
}

export function GetPendingCandidateCount() {
  return window['go']['main']['App']['GetPendingCandidateCount']();
}

export function GetPendingDigest() {
  return window['go']['main']['App']['GetPendingDigest']();
}

export function GetPendingTagPatches() {
  return window['go']['main']['App']['GetPendingTagPatches']();
}

export function GetPixelAvatarPack() {
  return window['go']['main']['App']['GetPixelAvatarPack']();
}

export function GetPixelAvatarPath(arg1, arg2) {
  return window['go']['main']['App']['GetPixelAvatarPath'](arg1, arg2);
}

export function GetProjectAllowlist() {
  return window['go']['main']['App']['GetProjectAllowlist']();
}

export function GetReadinessGateState() {
  return window['go']['main']['App']['GetReadinessGateState']();
}

export function GetRecentSkillInjections(arg1) {
  return window['go']['main']['App']['GetRecentSkillInjections'](arg1);
}

export function GetRemoteBridgeAudit(arg1) {
  return window['go']['main']['App']['GetRemoteBridgeAudit'](arg1);
}

export function GetRemoteBridgeInboundEndpoint(arg1) {
  return window['go']['main']['App']['GetRemoteBridgeInboundEndpoint'](arg1);
}

export function GetReviewExecutionContext(arg1) {
  return window['go']['main']['App']['GetReviewExecutionContext'](arg1);
}

export function GetSafariRuntimeNotice() {
  return window['go']['main']['App']['GetSafariRuntimeNotice']();
}

export function GetSettingsState() {
  return window['go']['main']['App']['GetSettingsState']();
}

export function GetSidecarState() {
  return window['go']['main']['App']['GetSidecarState']();
}

export function GetStopRecoveryCard(arg1) {
  return window['go']['main']['App']['GetStopRecoveryCard'](arg1);
}

export function GetSubExportCapabilities() {
  return window['go']['main']['App']['GetSubExportCapabilities']();
}

export function GetSubExportDesktopDirectory() {
  return window['go']['main']['App']['GetSubExportDesktopDirectory']();
}

export function GetSubExportFallbackDirectory() {
  return window['go']['main']['App']['GetSubExportFallbackDirectory']();
}

export function GetSummaryModelSettings() {
  return window['go']['main']['App']['GetSummaryModelSettings']();
}

export function GetTTSPackStatus() {
  return window['go']['main']['App']['GetTTSPackStatus']();
}

export function GetTabOrder() {
  return window['go']['main']['App']['GetTabOrder']();
}

export function GetTalkMessagesForAgent(arg1) {
  return window['go']['main']['App']['GetTalkMessagesForAgent'](arg1);
}

export function GetToolRegistryPatchProposals() {
  return window['go']['main']['App']['GetToolRegistryPatchProposals']();
}

export function GetToolVisibility() {
  return window['go']['main']['App']['GetToolVisibility']();
}

export function GetUISettings() {
  return window['go']['main']['App']['GetUISettings']();
}

export function GetURLProvenance(arg1) {
  return window['go']['main']['App']['GetURLProvenance'](arg1);
}

export function GetVoiceSettings() {
  return window['go']['main']['App']['GetVoiceSettings']();
}

export function GetW3ATransferGuidance() {
  return window['go']['main']['App']['GetW3ATransferGuidance']();
}

export function GetWebSearchConfig() {
  return window['go']['main']['App']['GetWebSearchConfig']();
}

export function GetYOLODetailedStatus() {
  return window['go']['main']['App']['GetYOLODetailedStatus']();
}

export function GetYOLOStatus() {
  return window['go']['main']['App']['GetYOLOStatus']();
}

export function GoBackOnboarding() {
  return window['go']['main']['App']['GoBackOnboarding']();
}

export function HandleDocumentDrop(arg1) {
  return window['go']['main']['App']['HandleDocumentDrop'](arg1);
}

export function HasAvatarCredential(arg1) {
  return window['go']['main']['App']['HasAvatarCredential'](arg1);
}

export function HasBlockingReviewCard() {
  return window['go']['main']['App']['HasBlockingReviewCard']();
}

export function HasBlockingVLReview() {
  return window['go']['main']['App']['HasBlockingVLReview']();
}

export function HasOpenStopRecoveryCard() {
  return window['go']['main']['App']['HasOpenStopRecoveryCard']();
}

export function ImportGoProgramExport(arg1) {
  return window['go']['main']['App']['ImportGoProgramExport'](arg1);
}

export function ImportLearningRunExport(arg1) {
  return window['go']['main']['App']['ImportLearningRunExport'](arg1);
}

export function ImportMediaVerify(arg1) {
  return window['go']['main']['App']['ImportMediaVerify'](arg1);
}

export function ImportProjectBackupHandler(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportProjectBackupHandler'](arg1, arg2, arg3);
}

export function ImportReferenceFile(arg1) {
  return window['go']['main']['App']['ImportReferenceFile'](arg1);
}

export function ImportSubHandler(arg1) {
  return window['go']['main']['App']['ImportSubHandler'](arg1);
}

export function ImportVideoFile(arg1) {
  return window['go']['main']['App']['ImportVideoFile'](arg1);
}

export function InspectProjectBackupHandler(arg1, arg2) {
  return window['go']['main']['App']['InspectProjectBackupHandler'](arg1, arg2);
}

export function InstallTTSPack() {
  return window['go']['main']['App']['InstallTTSPack']();
}

export function InstallVoiceBaseModel() {
  return window['go']['main']['App']['InstallVoiceBaseModel']();
}

export function InvalidateDualStep(arg1) {
  return window['go']['main']['App']['InvalidateDualStep'](arg1);
}

export function IsDegradedBlocked(arg1) {
  return window['go']['main']['App']['IsDegradedBlocked'](arg1);
}

export function IsDocumentFormat(arg1) {
  return window['go']['main']['App']['IsDocumentFormat'](arg1);
}

export function IsLearningModeActive() {
  return window['go']['main']['App']['IsLearningModeActive']();
}

export function IsLivePreviewActive() {
  return window['go']['main']['App']['IsLivePreviewActive']();
}

export function IsProjectBackupEncryptedHandler(arg1) {
  return window['go']['main']['App']['IsProjectBackupEncryptedHandler'](arg1);
}

export function IsReadOnlyMode() {
  return window['go']['main']['App']['IsReadOnlyMode']();
}

export function ListAdapterModelOptions(arg1) {
  return window['go']['main']['App']['ListAdapterModelOptions'](arg1);
}

export function ListArchivedSkills() {
  return window['go']['main']['App']['ListArchivedSkills']();
}

export function ListAvailableAdapters() {
  return window['go']['main']['App']['ListAvailableAdapters']();
}

export function ListAvatarPresets() {
  return window['go']['main']['App']['ListAvatarPresets']();
}

export function ListDAGRuns() {
  return window['go']['main']['App']['ListDAGRuns']();
}

export function ListDAGRunsFromIndex(arg1, arg2) {
  return window['go']['main']['App']['ListDAGRunsFromIndex'](arg1, arg2);
}

export function ListElementDictionary(arg1) {
  return window['go']['main']['App']['ListElementDictionary'](arg1);
}

export function ListExternalLinksByType(arg1) {
  return window['go']['main']['App']['ListExternalLinksByType'](arg1);
}

export function ListFormalActions() {
  return window['go']['main']['App']['ListFormalActions']();
}

export function ListGoProgramAuthoringCatalog(arg1) {
  return window['go']['main']['App']['ListGoProgramAuthoringCatalog'](arg1);
}

export function ListInstalledEmbedModels() {
  return window['go']['main']['App']['ListInstalledEmbedModels']();
}

export function ListLLMProviderWhitelist() {
  return window['go']['main']['App']['ListLLMProviderWhitelist']();
}

export function ListLearningReplayCatalog(arg1) {
  return window['go']['main']['App']['ListLearningReplayCatalog'](arg1);
}

export function ListOpenLightweightCards() {
  return window['go']['main']['App']['ListOpenLightweightCards']();
}

export function ListOpenReviewCards() {
  return window['go']['main']['App']['ListOpenReviewCards']();
}

export function ListOpenStopRecoveryCards() {
  return window['go']['main']['App']['ListOpenStopRecoveryCards']();
}

export function ListOpenVLReviewCards() {
  return window['go']['main']['App']['ListOpenVLReviewCards']();
}

export function ListPendingActions() {
  return window['go']['main']['App']['ListPendingActions']();
}

export function ListPendingCandidates() {
  return window['go']['main']['App']['ListPendingCandidates']();
}

export function ListPendingPackages() {
  return window['go']['main']['App']['ListPendingPackages']();
}

export function ListPixelAvatarPacks() {
  return window['go']['main']['App']['ListPixelAvatarPacks']();
}

export function ListProjectDocuments() {
  return window['go']['main']['App']['ListProjectDocuments']();
}

export function ListPurgeManifests() {
  return window['go']['main']['App']['ListPurgeManifests']();
}

export function ListReferenceFiles() {
  return window['go']['main']['App']['ListReferenceFiles']();
}

export function ListReferenceImages() {
  return window['go']['main']['App']['ListReferenceImages']();
}

export function ListRemoteBridgeChannels() {
  return window['go']['main']['App']['ListRemoteBridgeChannels']();
}

export function ListRemoteBridgeInboundAdapters() {
  return window['go']['main']['App']['ListRemoteBridgeInboundAdapters']();
}

export function ListRemoteBridgePresets() {
  return window['go']['main']['App']['ListRemoteBridgePresets']();
}

export function ListReviewArchive() {
  return window['go']['main']['App']['ListReviewArchive']();
}

export function ListScheduledJobs() {
  return window['go']['main']['App']['ListScheduledJobs']();
}

export function ListThreatRecords() {
  return window['go']['main']['App']['ListThreatRecords']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function ListVideoFiles() {
  return window['go']['main']['App']['ListVideoFiles']();
}

export function ListW3ATrustedDevelopers() {
  return window['go']['main']['App']['ListW3ATrustedDevelopers']();
}

export function MapCanonicalLabel(arg1, arg2, arg3) {
  return window['go']['main']['App']['MapCanonicalLabel'](arg1, arg2, arg3);
}

export function MarkSkillFirstUseExplained() {
  return window['go']['main']['App']['MarkSkillFirstUseExplained']();
}

export function MarkToolAvailable(arg1) {
  return window['go']['main']['App']['MarkToolAvailable'](arg1);
}

export function MarkToolUnavailable(arg1, arg2) {
  return window['go']['main']['App']['MarkToolUnavailable'](arg1, arg2);
}

export function NativeDragExportGoProgramAuthoring(arg1) {
  return window['go']['main']['App']['NativeDragExportGoProgramAuthoring'](arg1);
}

export function NativeDragExportLearningRun(arg1) {
  return window['go']['main']['App']['NativeDragExportLearningRun'](arg1);
}

export function NativeDragExportPersonaHandler(arg1, arg2) {
  return window['go']['main']['App']['NativeDragExportPersonaHandler'](arg1, arg2);
}

export function NativeDragExportReferenceFile(arg1) {
  return window['go']['main']['App']['NativeDragExportReferenceFile'](arg1);
}

export function NativeDragExportSkill(arg1) {
  return window['go']['main']['App']['NativeDragExportSkill'](arg1);
}

export function NativeDragExportSubHandler(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NativeDragExportSubHandler'](arg1, arg2, arg3, arg4);
}

export function NextGreeting(arg1) {
  return window['go']['main']['App']['NextGreeting'](arg1);
}

export function NotifyStatusRail(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NotifyStatusRail'](arg1, arg2, arg3, arg4);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function PauseScheduledJob(arg1) {
  return window['go']['main']['App']['PauseScheduledJob'](arg1);
}

export function PollStatusRail() {
  return window['go']['main']['App']['PollStatusRail']();
}

export function PollTelegramChatID(arg1) {
  return window['go']['main']['App']['PollTelegramChatID'](arg1);
}

export function PrepareAvatarGenerateRequest(arg1, arg2) {
  return window['go']['main']['App']['PrepareAvatarGenerateRequest'](arg1, arg2);
}

export function PrepareCloudTTSText(arg1) {
  return window['go']['main']['App']['PrepareCloudTTSText'](arg1);
}

export function PreparePackageInstall(arg1, arg2) {
  return window['go']['main']['App']['PreparePackageInstall'](arg1, arg2);
}

export function PreparePackageInstallPayload(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreparePackageInstallPayload'](arg1, arg2, arg3);
}

export function PreviewExternalLink(arg1) {
  return window['go']['main']['App']['PreviewExternalLink'](arg1);
}

export function PreviewGoProgramExport(arg1) {
  return window['go']['main']['App']['PreviewGoProgramExport'](arg1);
}

export function PreviewLearningRunExport(arg1) {
  return window['go']['main']['App']['PreviewLearningRunExport'](arg1);
}

export function PreviewSubPackage(arg1) {
  return window['go']['main']['App']['PreviewSubPackage'](arg1);
}

export function PromoteDraftToPending(arg1, arg2) {
  return window['go']['main']['App']['PromoteDraftToPending'](arg1, arg2);
}

export function ProposeRegions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProposeRegions'](arg1, arg2, arg3);
}

export function PullEmbedModel(arg1) {
  return window['go']['main']['App']['PullEmbedModel'](arg1);
}

export function PurgeBoundaryDir(arg1) {
  return window['go']['main']['App']['PurgeBoundaryDir'](arg1);
}

export function PurgeProject(arg1, arg2) {
  return window['go']['main']['App']['PurgeProject'](arg1, arg2);
}

export function ReadDocumentContent(arg1) {
  return window['go']['main']['App']['ReadDocumentContent'](arg1);
}

export function RecognizeNativeOCR(arg1) {
  return window['go']['main']['App']['RecognizeNativeOCR'](arg1);
}

export function RecordLearningMouseEvent(arg1) {
  return window['go']['main']['App']['RecordLearningMouseEvent'](arg1);
}

export function RecordMainInteraction(arg1, arg2) {
  return window['go']['main']['App']['RecordMainInteraction'](arg1, arg2);
}

export function RecordStepTrace(arg1, arg2) {
  return window['go']['main']['App']['RecordStepTrace'](arg1, arg2);
}

export function RefreshPendingCandidateAges() {
  return window['go']['main']['App']['RefreshPendingCandidateAges']();
}

export function RegisterCustomCLI(arg1, arg2) {
  return window['go']['main']['App']['RegisterCustomCLI'](arg1, arg2);
}

export function RegisterExternalLink(arg1, arg2) {
  return window['go']['main']['App']['RegisterExternalLink'](arg1, arg2);
}

export function RegisterLLMAPIAdapter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterLLMAPIAdapter'](arg1, arg2, arg3, arg4, arg5);
}

export function RegisterRemoteBridgeChannel(arg1) {
  return window['go']['main']['App']['RegisterRemoteBridgeChannel'](arg1);
}

export function RegisterRemoteBridgeChannelWithMode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegisterRemoteBridgeChannelWithMode'](arg1, arg2, arg3, arg4);
}

export function RegisterSchedulerCallback(arg1) {
  return window['go']['main']['App']['RegisterSchedulerCallback'](arg1);
}

export function RegisterURLOccurrence(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegisterURLOccurrence'](arg1, arg2, arg3, arg4);
}

export function RejectPackageInstall(arg1, arg2) {
  return window['go']['main']['App']['RejectPackageInstall'](arg1, arg2);
}

export function RemoveAllowlistEntry(arg1) {
  return window['go']['main']['App']['RemoveAllowlistEntry'](arg1);
}

export function RemoveRemoteBridgeChannel(arg1) {
  return window['go']['main']['App']['RemoveRemoteBridgeChannel'](arg1);
}

export function RemoveTTSPack() {
  return window['go']['main']['App']['RemoveTTSPack']();
}

export function RemoveTabOrder(arg1) {
  return window['go']['main']['App']['RemoveTabOrder'](arg1);
}

export function RemoveVoiceBaseModel() {
  return window['go']['main']['App']['RemoveVoiceBaseModel']();
}

export function RenameAdapter(arg1, arg2) {
  return window['go']['main']['App']['RenameAdapter'](arg1, arg2);
}

export function RenameRemoteBridgeChannel(arg1, arg2) {
  return window['go']['main']['App']['RenameRemoteBridgeChannel'](arg1, arg2);
}

export function RenameSubagent(arg1, arg2) {
  return window['go']['main']['App']['RenameSubagent'](arg1, arg2);
}

export function RenderPixelAvatar(arg1, arg2) {
  return window['go']['main']['App']['RenderPixelAvatar'](arg1, arg2);
}

export function RenderPixelAvatarPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderPixelAvatarPreview'](arg1, arg2, arg3);
}

export function RenewAllowlistEntry(arg1) {
  return window['go']['main']['App']['RenewAllowlistEntry'](arg1);
}

export function ReorderAdapters(arg1) {
  return window['go']['main']['App']['ReorderAdapters'](arg1);
}

export function ReorderPersonas(arg1) {
  return window['go']['main']['App']['ReorderPersonas'](arg1);
}

export function ReorderTabs(arg1) {
  return window['go']['main']['App']['ReorderTabs'](arg1);
}

export function ResolveAndExecuteDestructiveReviewCard(arg1, arg2) {
  return window['go']['main']['App']['ResolveAndExecuteDestructiveReviewCard'](arg1, arg2);
}

export function ResolveImportToolConflict(arg1) {
  return window['go']['main']['App']['ResolveImportToolConflict'](arg1);
}

export function ResolveImportToolConflicts(arg1) {
  return window['go']['main']['App']['ResolveImportToolConflicts'](arg1);
}

export function ResolveLightweightCard(arg1) {
  return window['go']['main']['App']['ResolveLightweightCard'](arg1);
}

export function ResolveReviewCard(arg1) {
  return window['go']['main']['App']['ResolveReviewCard'](arg1);
}

export function ResolveSkillForAction(arg1, arg2) {
  return window['go']['main']['App']['ResolveSkillForAction'](arg1, arg2);
}

export function ResolveStopRecoveryCard(arg1, arg2) {
  return window['go']['main']['App']['ResolveStopRecoveryCard'](arg1, arg2);
}

export function ResolveVLReviewCard(arg1) {
  return window['go']['main']['App']['ResolveVLReviewCard'](arg1);
}

export function ResolveWindowsClickAnchor(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ResolveWindowsClickAnchor'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RestartSidecar() {
  return window['go']['main']['App']['RestartSidecar']();
}

export function RestoreUIDefaults() {
  return window['go']['main']['App']['RestoreUIDefaults']();
}

export function ResumeDAGRun(arg1) {
  return window['go']['main']['App']['ResumeDAGRun'](arg1);
}

export function ResumeScheduledJob(arg1) {
  return window['go']['main']['App']['ResumeScheduledJob'](arg1);
}

export function RetryRemoteBridgeSegment(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetryRemoteBridgeSegment'](arg1, arg2, arg3);
}

export function RotateTalkFull() {
  return window['go']['main']['App']['RotateTalkFull']();
}

export function RouteVoiceCommand(arg1) {
  return window['go']['main']['App']['RouteVoiceCommand'](arg1);
}

export function RunGoProgramAuthoringLoop(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunGoProgramAuthoringLoop'](arg1, arg2, arg3, arg4, arg5);
}

export function RunPackageSecurityCheck(arg1) {
  return window['go']['main']['App']['RunPackageSecurityCheck'](arg1);
}

export function RunSummarizationNow(arg1) {
  return window['go']['main']['App']['RunSummarizationNow'](arg1);
}

export function SaveDocumentFromAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDocumentFromAgent'](arg1, arg2, arg3);
}

export function SaveMainAsSub(arg1) {
  return window['go']['main']['App']['SaveMainAsSub'](arg1);
}

export function SavePanelSettings(arg1) {
  return window['go']['main']['App']['SavePanelSettings'](arg1);
}

export function SavePersona(arg1) {
  return window['go']['main']['App']['SavePersona'](arg1);
}

export function SaveRemoteBridgeInboundSecret(arg1, arg2) {
  return window['go']['main']['App']['SaveRemoteBridgeInboundSecret'](arg1, arg2);
}

export function SaveStaticAvatar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveStaticAvatar'](arg1, arg2, arg3, arg4);
}

export function SaveSummaryModelSettings(arg1) {
  return window['go']['main']['App']['SaveSummaryModelSettings'](arg1);
}

export function SaveVoiceSettings(arg1) {
  return window['go']['main']['App']['SaveVoiceSettings'](arg1);
}

export function SaveWebSearchConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWebSearchConfig'](arg1, arg2, arg3);
}

export function ScanLocalModels() {
  return window['go']['main']['App']['ScanLocalModels']();
}

export function ScanLocalSummaryModels() {
  return window['go']['main']['App']['ScanLocalSummaryModels']();
}

export function ScanOrphanQuarantine() {
  return window['go']['main']['App']['ScanOrphanQuarantine']();
}

export function ScanSkillFolder(arg1) {
  return window['go']['main']['App']['ScanSkillFolder'](arg1);
}

export function SearchLearningOperations(arg1, arg2) {
  return window['go']['main']['App']['SearchLearningOperations'](arg1, arg2);
}

export function SearchWeb(arg1, arg2) {
  return window['go']['main']['App']['SearchWeb'](arg1, arg2);
}

export function SearchWebConfirmed(arg1, arg2) {
  return window['go']['main']['App']['SearchWebConfirmed'](arg1, arg2);
}

export function SelectFloatingCandidate(arg1) {
  return window['go']['main']['App']['SelectFloatingCandidate'](arg1);
}

export function SelectPersonaExportDirectory() {
  return window['go']['main']['App']['SelectPersonaExportDirectory']();
}

export function SelectProjectBackupExportDirectory() {
  return window['go']['main']['App']['SelectProjectBackupExportDirectory']();
}

export function SelectProjectBackupFile() {
  return window['go']['main']['App']['SelectProjectBackupFile']();
}

export function SelectSubExportDirectory() {
  return window['go']['main']['App']['SelectSubExportDirectory']();
}

export function SendAPIMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendAPIMessage'](arg1, arg2, arg3, arg4);
}

export function SendCLIMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendCLIMessage'](arg1, arg2, arg3, arg4);
}

export function SendInspectorAPIMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendInspectorAPIMessage'](arg1, arg2, arg3, arg4);
}

export function SendInspectorMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendInspectorMessage'](arg1, arg2, arg3, arg4);
}

export function SendTopInteractionMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendTopInteractionMessage'](arg1, arg2, arg3, arg4);
}

export function SetActiveConversationAgent(arg1) {
  return window['go']['main']['App']['SetActiveConversationAgent'](arg1);
}

export function SetAdapterModelChoice(arg1, arg2) {
  return window['go']['main']['App']['SetAdapterModelChoice'](arg1, arg2);
}

export function SetAdapterStatus(arg1, arg2) {
  return window['go']['main']['App']['SetAdapterStatus'](arg1, arg2);
}

export function SetAvatarProvider(arg1, arg2) {
  return window['go']['main']['App']['SetAvatarProvider'](arg1, arg2);
}

export function SetBrowserPreference(arg1, arg2) {
  return window['go']['main']['App']['SetBrowserPreference'](arg1, arg2);
}

export function SetEmbeddingConfig(arg1, arg2) {
  return window['go']['main']['App']['SetEmbeddingConfig'](arg1, arg2);
}

export function SetPersonaPixelAvatarPack(arg1, arg2) {
  return window['go']['main']['App']['SetPersonaPixelAvatarPack'](arg1, arg2);
}

export function SetPixelAvatarPack(arg1) {
  return window['go']['main']['App']['SetPixelAvatarPack'](arg1);
}

export function SetRemoteBridgePrimaryChannel(arg1) {
  return window['go']['main']['App']['SetRemoteBridgePrimaryChannel'](arg1);
}

export function SetToolPreference(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetToolPreference'](arg1, arg2, arg3, arg4);
}

export function SetTrustDomAndClick(arg1) {
  return window['go']['main']['App']['SetTrustDomAndClick'](arg1);
}

export function StageSessionImages(arg1, arg2) {
  return window['go']['main']['App']['StageSessionImages'](arg1, arg2);
}

export function StartDraftSandbox(arg1) {
  return window['go']['main']['App']['StartDraftSandbox'](arg1);
}

export function StartGoProgramAuthoring(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartGoProgramAuthoring'](arg1, arg2, arg3);
}

export function StartHookRun(arg1, arg2) {
  return window['go']['main']['App']['StartHookRun'](arg1, arg2);
}

export function StartLearningMode(arg1) {
  return window['go']['main']['App']['StartLearningMode'](arg1);
}

export function StartLivePreview(arg1) {
  return window['go']['main']['App']['StartLivePreview'](arg1);
}

export function StartTaskProgress(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTaskProgress'](arg1, arg2, arg3, arg4);
}

export function StartTelegramOnboarding(arg1) {
  return window['go']['main']['App']['StartTelegramOnboarding'](arg1);
}

export function StartURLVisualLearning(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartURLVisualLearning'](arg1, arg2, arg3);
}

export function StopDraftSandbox(arg1, arg2) {
  return window['go']['main']['App']['StopDraftSandbox'](arg1, arg2);
}

export function StopLearningMode() {
  return window['go']['main']['App']['StopLearningMode']();
}

export function StopSidecar() {
  return window['go']['main']['App']['StopSidecar']();
}

export function StopURLVisualLearning() {
  return window['go']['main']['App']['StopURLVisualLearning']();
}

export function StoreAvatarCredential(arg1, arg2) {
  return window['go']['main']['App']['StoreAvatarCredential'](arg1, arg2);
}

export function SubmitTaskLoopInput(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitTaskLoopInput'](arg1, arg2, arg3);
}

export function SwitchRemoteBridgeMode(arg1, arg2) {
  return window['go']['main']['App']['SwitchRemoteBridgeMode'](arg1, arg2);
}

export function TestRemoteBridgeConnection(arg1) {
  return window['go']['main']['App']['TestRemoteBridgeConnection'](arg1);
}

export function TranscribeVoiceWAV(arg1, arg2) {
  return window['go']['main']['App']['TranscribeVoiceWAV'](arg1, arg2);
}

export function UnregisterAdapter(arg1) {
  return window['go']['main']['App']['UnregisterAdapter'](arg1);
}

export function UpdateDAGNodeStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDAGNodeStatus'](arg1, arg2, arg3);
}

export function UpdateLearningRunMetadata(arg1) {
  return window['go']['main']['App']['UpdateLearningRunMetadata'](arg1);
}

export function ValidateMemoryItem(arg1) {
  return window['go']['main']['App']['ValidateMemoryItem'](arg1);
}

export function VerifyMediaFile(arg1) {
  return window['go']['main']['App']['VerifyMediaFile'](arg1);
}

export function WakeLocalAdapter(arg1) {
  return window['go']['main']['App']['WakeLocalAdapter'](arg1);
}

export function WakeOllamaDaemon() {
  return window['go']['main']['App']['WakeOllamaDaemon']();
}
